[package]
name = "nd_lib"
version = "0.1.0"
authors = ["Jeff Dickey <@jdxcode>"]

[dependencies]
serde = "1.0.79"
serde_json = "1.0.30"
serde_derive = "1.0.79"
log = "0.4.5"
env_logger = "0.5.13"

[dev-dependencies]
matches = "0.1.8"
